const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const siteDir = path.resolve(__dirname, "..", "_site");
const homepage = fs.readFileSync(path.join(siteDir, "index.html"), "utf8");
const publications = fs.readFileSync(
  path.join(siteDir, "publications", "index.html"),
  "utf8",
);
const cv = fs.readFileSync(path.join(siteDir, "cv", "index.html"), "utf8");
const news = fs.readFileSync(path.join(siteDir, "news", "index.html"), "utf8");

test("homepage presents durable and accessible biographical details", () => {
  assert.doesNotMatch(homepage, /first-year Ph\.D\. student/);
  assert.match(homepage, /I am a Ph\.D\. student in Computer Science at/);
  assert.match(
    homepage,
    /href="https:\/\/www\.cs\.usc\.edu\/"[^>]*>University of Southern California<\/a>/,
  );
  assert.match(homepage, /alt="Portrait of Qingchuan \(Tony\) Yang"/);
});

test("publications page contains no starter-template interface", () => {
  assert.doesNotMatch(publications, /generated by jekyll-scholar/i);
  assert.doesNotMatch(publications, /id="bibsearch"/);
});

test("publication entries expose scholarly artifacts and contribution notes", () => {
  assert.equal(
    (publications.match(/class="bibtex btn btn-sm z-depth-0"/g) || []).length,
    4,
  );
  assert.match(
    publications,
    /class="abstract btn btn-sm z-depth-0"[^>]*>Abstract<\/a>/,
  );
  assert.doesNotMatch(publications, />Abs<\/a>/);
  assert.equal((publications.match(/>BibTeX<\/a>/g) || []).length, 4);
  assert.doesNotMatch(publications, />Bib<\/a>/);
  assert.match(
    publications,
    /<p class="publication-note"><sup>\*<\/sup> Equal contribution\.<\/p>/,
  );
});

test("news links Prophet Arena's Inkling benchmark mention to its source", () => {
  assert.match(
    news,
    /href="https:\/\/thinkingmachines\.ai\/news\/introducing-inkling\/"[^>]*>Inkling release<\/a>/,
  );
});

test("Prophet Arena's publication entry links the Inkling feature", () => {
  assert.match(
    publications,
    /href="https:\/\/thinkingmachines\.ai\/news\/introducing-inkling\/"[^>]*>Thinking Machines Lab(?:'s|’s) Inkling release<\/a>/,
  );
});

test("CV dates and controls are clear without empty location markers", () => {
  assert.match(cv, /aria-label="Download CV as PDF"/);
  assert.match(cv, />May&ndash;Aug 2026<|>May–Aug 2026</);
  assert.match(cv, />Jun&ndash;Sep 2023<|>Jun–Sep 2023</);
  assert.doesNotMatch(
    cv,
    /<p class="location">\s*<i class="fa-solid fa-location-dot iconlocation"><\/i>\s*<\/p>/,
  );
});
