# rendercv settings: https://docs.rendercv.com/user_guide/yaml_input_structure/settings/
settings:
  render_command:
    # Paths are relative to _data/cv.yml
    design: ../assets/rendercv/design.yaml
    locale: ../assets/rendercv/locale.yaml
    typst_path: ../assets/rendercv/rendercv_output/cv.typ
    pdf_path: ../assets/pdf/Qingchuan_Tony_Yang_CV.pdf
    dont_generate_markdown: true
    dont_generate_html: true
    dont_generate_typst: false
    dont_generate_pdf: false
    dont_generate_png: true
  bold_keywords: []
